setStyle endpoint
GreyMatteOr/Crate pull request #59
Opened 2020-12-07 22:41 UTC by lkriffell

Creates the setStyle endpoint for FE. It takes id and style (as a string) as args.
If the style is a blank string it throws an error

![Screen Shot 2020-12-07 at 3 28 41 PM](https://user-images.githubusercontent.com/61526543/101413079-e605e180-38a0-11eb-847b-718e2271d269.png)
Example of what the graphQL response looks like.

To install the Sequelize CLI tools, from the root directory, navigate to code/api/ and in terminal type npm install --save-dev sequelize-cli. Afterwards, please run the following commands in order:

npx sequelize db:seed:undo:all
npx sequelize db:migrate
npx sequelize db:seed:all

From there you can npm start and run the query using GraphiQL

This pr does not close any issues as testing has yet to be implemented

2020-12-07 23:15 UTC, hashmaster3k commented
@lkriffell by ID you mean the user's ID?

2020-12-07 23:16 UTC, lkriffell commented
> @lkriffell the ID needed in the argument is the user's ID correct?

Yes

2020-12-07 23:16 UTC, hashmaster3k commented on code/api/src/migrations/1-user.js
> +  // Provides a way to rollback if needed
Good idea on the comments to keep the code more approachable!

2020-12-09 15:59 UTC, hashmaster3k commented on code/api/src/modules/tests/user/mutation.test.js
> +
Remove this commented out code?

2020-12-09 16:01 UTC, hashmaster3k commented on code/api/src/modules/user/model.js
> +// Model for user. Defines the types they are in the DB. Also defines associations between other resources such as Subscriptions
Maybe we should remove these extra annotations?

2020-12-09 16:01 UTC, hashmaster3k commented on code/api/src/modules/user/mutations.js
> +}
Looks good!

2020-12-09 16:02 UTC, hashmaster3k commented on code/api/src/modules/user/resolvers.js
> +
This work around for now will allow for returning non-null response:

`export async function updateStyle(parentValue, { style, id }) {
  if (style !== "") {
    await models.User.update(
      {
        style
      },
      { where: { id } }
    );
    return await models.User.findOne({ where: { id } })
  } else {
    throw new Error(`You must enter a style to set a user's style`)
  }
}`

2020-12-09 16:04 UTC, hashmaster3k commented on code/api/src/modules/user/types.js
> +    style: { type: GraphQLString },
Defined twice, see line 20 below. Please remove one or the other.

2020-12-09 16:05 UTC, hashmaster3k requested changes
Looks good overall, requests to make a few changes regarding extra annotations, setStyle function and an repeated type.

2020-12-09 18:08 UTC, hashmaster3k approved these changes

2020-12-09 18:19 UTC, merged